# See https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  RunRailsCops: true
  DisplayCopNames: true

  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/spring'
    - 'app/views/pages/getting_started/templates/**/*'

Metrics/ClassLength:
  # 'Avoid classes longer than 100 lines of code.'
  Enabled: false

Metrics/LineLength:
  # 'Limit lines to 100 characters.'
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/AlignHash:
  # 'Align the elements of a hash literal if they span more than one line.'
  Enabled: false # This is a nice-to-have, not something we want to enforce

Style/AsciiComments:
  Enabled: false # We want to allow for UTF-8 in comments

Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    collect:  'map'
    collect!: 'map!'
    find:     'detect'
    find_all: 'select'
    reduce:   'inject'
    size:     'length'

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyLines:
  Enabled: false # We often use multiple empty lines to group chunks of code

Style/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - 'bin/*'

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/WordArray:
  MinSize: 3
