# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e861be81c909e1fdfef6d2af5121814c9017f1ba06e2c843056493c1ade8fb33e9c7bc9b0b1bf5f49acaf49d7da65db34b93e7a8b0e560b57530afd4606dcbff

test:
  secret_key_base: 55ac2a5062a6946e3f668dbdb218bd7e2700a018a4e23d18208273f3079d7dc5ddbc12229f1ea2ebfca577fdaf5cadd39ec66c1cb64fa33a1d974aba058e31d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
